PATCH http://localhost:8080/api/user/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2MDcwMDI0MDcsImV4cCI6MTYwNzAwNjAwN30.s-UDZIBbb8DqZeIcRtx7CXhkdhTvxm1gCvde8L5-0AQ
Content-Type: application/json

{"firstName":"Nikita","lastName":"Maslov","email":"maslov.e.f@gmail.com","passwordObj":{"currentPassword":"55&2020","newPassword":"Nikmas&23032002","repeat":"Nikmas&23032002"},"displayName":"Nikmas"}
